name: Refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '50 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget 'https://raw.githubusercontent.com/saschazesiger/Proxy-Grabber-and-Checker/main/Sources.txt'
          wget 'https://raw.githubusercontent.com/saschazesiger/Proxy-Grabber-and-Checker/main/chromedriver'
          wget 'https://raw.githubusercontent.com/saschazesiger/Proxy-Grabber-and-Checker/main/refresh.py'
          wget 'https://github.com/saschazesiger/Proxy-Grabber-and-Checker/blob/main/readme-template.me'
          mv readme-template.me readme.me
          pip install requests beautifulsoup4 selenium
      - name: Run
        run: |
          chmod 777 chromedriver
          python refresh.py
      - name: Commit
        run: |
          git config --local user.email 'saschazesiger@users.noreply.github.com'
          git config --local user.name 'saschazesiger'
          git remote set-url origin 'https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/saschazesiger/Free-Proxies.git'
          git add 'proxies/'
          git add 'readme.me'
          git commit -am "Refreshed List"
          git push
